name: 🚀 Laravel Deploy

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:
    inputs:
      # branch:
      #   description: "Branch to deploy to"
      #   required: true
      messages:
        description: "Type deployment messages"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Set Up PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.1' # Ganti dengan versi PHP yang sesuai dengan Laravel 9

      # - name: Install Dependencies
      #   run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # - name: Generate Environment File
      #   run: cp .env.example .env

      # - name: Generate Application Key
      #   run: php artisan key:generate

      # # - name: Run Database Migrations
      # #   run: php artisan migrate --force

      # - name: Cache Configuration
      #   run: php artisan config:cache

      # - name: Clear Route Cache
      #   run: php artisan route:cache

      # - name: Clear Known Hosts
      #   run: ssh-keygen -R laravel9.jasatebangpohonjabodetabek.com

      # - name: Verify and Update Known Hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     touch ~/.ssh/known_hosts
      #     ssh-keyscan -p 2223 laravel9.jasatebangpohonjabodetabek.com >> ~/.ssh/known_hosts

      # - name: SSH into Remote Server
      #   run: |
      #    sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -p ${{ secrets.SSH_PORT }} jass8211@laravel9.jasatebangpohonjabodetabek.com "connection succes"

      # - name: Clear View Cache
      #   run: php artisan view:cache
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: laravel9.jasatebangpohonjabodetabek.com
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            cd /public_html/laravel9 && ls -al

      # - name: Deploy to Shared Hosting
      #   run: |
      #     sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -p ${{ secrets.SSH_PORT }} jass8211@laravel9.jasatebangpohonjabodetabek.com "cd /public_html/laravel9 && git pull origin master"
